version: 2.1

jobs: 
  build:
    docker: 
      - image: hashicorp/terraform   
    steps: 
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      - store-artifacts:
          path: terraform.tfstate
      
      - run:
          name: "apply"
          command: terraform apply --auto-approve
  build2:
    docker: 
      - image: hashicorp/terraform   
    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      
      
workflows: 
  build:
    jobs:
      - build:
          context: ENV_CRED_GCP
      - hold:
          type: approval 
          requires:
            - build
      - build2:
          
          requires: 
            - hold
            - build