version: 2.1
orbs:
  terraform: circleci/terraform@3.0.0
workflows:
  deploy_infrastructure:
    jobs:
      
      - terraform/validate:
          checkout: true
          context: dev_server_cred
      - terraform/init:
          checkout: true
          context: dev_server_cred
          requires:
            - terraform/validate
          
      - terraform/plan:
          checkout: true
          context: dev_server_cred
          persist-workspace: true
          requires:
            - terraform/validate
      - terraform/destroy:
          checkout: true
          context: dev_server_cred
          requires:
            - terraform/validate
            - terraform/plan
      - hold:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          attach-workspace: true
          context: dev_server_cred
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
            - hold
      
