version: 2.1

jobs: 
  build:
    docker: 
      - image: hashicorp/terraform   # this terraform image to run our project 
    steps: 
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      - run:
          name: "destroy"
          command: terraform destroy
      
  build2:
    docker: 
      - image: hashicorp/terraform   
    steps:
      - checkout 
      - run:
          name: "init"
          command: terraform init 
      - run:
          name: "plan"
          command: terraform plan
      - run:
          name: "apply"
          command: terraform apply --auto-approve 
workflows: 
  build:
    jobs:
      - build:
          context: dev_server_cred
      - hold:
          type: approval 
          requires:
            - build
      - build2:
          
          requires: 
            - hold
            - build